package fraymus.llm;

import fraymus.ollama.OllamaSpine;

/**
 * 🧠 AEON PRIME SPINE
 * 
 * Exposes AEON Prime as a ModelInterface for code generation
 * Specializes in Fraynix-specific code and domain knowledge
 * Uses Ollama for actual code generation with domain knowledge focus
 */
public class AeonPrimeSpine implements ModelInterface {
    
    private final OllamaSpine ollamaSpine;
    private final String model;
    private int requestCount = 0;
    private long totalThinkTime = 0;
    
    /**
     * Create AEON Prime spine
     */
    public AeonPrimeSpine() {
        this.ollamaSpine = new OllamaSpine("llama3");
        this.model = "aeon-prime-internal";
        System.out.println(">>> [AEON PRIME SPINE] Initialized as code generation model + Ollama backend");
    }
    
    /**
     * Generate AEON Prime response
     */
    @Override
    public String generateResponse(String prompt) {
        return generateResponse(prompt, "");
    }
    
    /**
     * Generate AEON Prime response with context
     */
    @Override
    public String generateResponse(String prompt, String context) {
        long startTime = System.currentTimeMillis();
        requestCount++;
        
        try {
            // Analyze prompt for Fraynix-specific content
            String domainPrompt = analyzeForDomainKnowledge(prompt);
            
            // Generate actual code using Ollama with domain knowledge focus
            String domainContext = "You are an expert on the Fraynix AGI system. Generate code that integrates with Fraynix components: AEON Prime, HyperCortex, Genesis Drive, AkashicRecord. Focus on: internal APIs, system integration, domain-specific patterns. " + context;
            String response = ollamaSpine.think(domainPrompt, domainContext);
            
            long thinkTime = System.currentTimeMillis() - startTime;
            totalThinkTime += thinkTime;
            
            System.out.println(">>> [AEON PRIME] Domain knowledge applied in " + thinkTime + "ms");
            
            return response;
            
        } catch (Exception e) {
            System.err.println(">>> [AEON PRIME ERROR] " + e.getMessage());
            return generateDomainResponse(prompt, context); // Fallback to stub
        }
    }
    
    /**
     * Analyze prompt for Fraynix domain knowledge
     */
    private String analyzeForDomainKnowledge(String prompt) {
        // Add domain knowledge hints
        if (prompt.toLowerCase().contains("fraynix") || 
            prompt.toLowerCase().contains("aeon") ||
            prompt.toLowerCase().contains("cortex") ||
            prompt.toLowerCase().contains("hypercortex") ||
            prompt.toLowerCase().contains("genesis")) {
            return "// FRAYNIX DOMAIN SPECIFIC\n" + prompt;
        }
        return prompt;
    }
    
    /**
     * Generate domain-specific response
     */
    private String generateDomainResponse(String prompt, String context) {
        StringBuilder response = new StringBuilder();
        
        response.append("// Generated by AEON Prime (Domain Knowledge)\n");
        String taskDesc = prompt.replace("\n", " ").trim();
        if (taskDesc.length() > 50) {
            taskDesc = taskDesc.substring(0, 50);
        }
        response.append("// Task: ").append(taskDesc).append("...\n");
        if (!context.isEmpty()) {
            String contextDesc = context.trim();
            if (contextDesc.length() > 50) {
                contextDesc = contextDesc.substring(0, 50);
            }
            response.append("// Context: ").append(contextDesc).append("...\n");
        }
        response.append("\n");
        response.append("// Fraynix domain-specific code:\n");
        response.append("// - AEON Prime integration\n");
        response.append("// - HyperCortex compatibility\n");
        response.append("// - Genesis Drive persistence\n");
        response.append("// - Internal API usage\n");
        response.append("\n");
        response.append("// TODO: Implement domain-specific version\n");
        
        return response.toString();
    }
    
    /**
     * Get model name
     */
    @Override
    public String getModel() {
        return model;
    }
    
    /**
     * Set active model (not supported for AEON Prime)
     */
    @Override
    public void setModel(String modelName) {
        System.out.println(">>> [AEON PRIME] Model switching not supported");
    }
    
    /**
     * Get available models
     */
    @Override
    public String[] getAvailableModels() {
        return new String[] { "aeon-prime-internal" };
    }
    
    /**
     * Test connection
     */
    @Override
    public boolean testConnection() {
        return true; // Always available (internal system)
    }
    
    /**
     * Get statistics
     */
    @Override
    public ModelStats getStats() {
        long avgTime = requestCount > 0 ? totalThinkTime / requestCount : 0;
        return new ModelStats(model, requestCount, avgTime, testConnection());
    }
    
    /**
     * Print statistics
     */
    public void printStats() {
        System.out.println("╔═══════════════════════════════════════════════════════════╗");
        System.out.println("║   AEON PRIME SPINE STATISTICS                          ║");
        System.out.println("╚═══════════════════════════════════════════════════════════╝");
        System.out.println("  Model: " + model);
        System.out.println("  Available: " + (testConnection() ? "Yes" : "No"));
        System.out.println("  Requests: " + requestCount);
        System.out.println("  Avg Think Time: " + (requestCount > 0 ? totalThinkTime / requestCount : 0) + "ms");
        System.out.println("  Total Think Time: " + totalThinkTime + "ms");
    }
}
