package fraymus.llm;

import fraymus.compute.FrayCLContext;
import fraymus.ollama.OllamaSpine;

/**
 * 🐉 OPENCLAW SPINE
 * 
 * Performance optimization specialist using FrayCL compute abstraction
 * Specializes in code optimization and performance tuning
 * Uses Ollama for actual code generation with optimization focus
 */
public class OpenClawSpine implements ModelInterface {
    
    private final FrayCLContext computeContext;
    private final OllamaSpine ollamaSpine;
    private final String model;
    private int requestCount = 0;
    private long totalThinkTime = 0;
    
    /**
     * Create OpenClaw spine
     * 
     * @param computeContext FrayCL compute context
     */
    public OpenClawSpine(FrayCLContext computeContext) {
        this.computeContext = computeContext;
        this.ollamaSpine = new OllamaSpine("llama3");
        this.model = "openclaw-v1";
        System.out.println(">>> [OPENCLAW SPINE] Initialized with FrayCL compute + Ollama backend");
    }
    
    /**
     * Generate optimized response
     */
    @Override
    public String generateResponse(String prompt) {
        return generateResponse(prompt, "");
    }
    
    /**
     * Generate optimized response with context
     */
    @Override
    public String generateResponse(String prompt, String context) {
        long startTime = System.currentTimeMillis();
        requestCount++;
        
        try {
            // Analyze prompt for optimization opportunities
            String optimizedPrompt = analyzeForOptimization(prompt);
            
            // Use FrayCL for parallel analysis if available
            if (computeContext != null) {
                optimizedPrompt = applyComputeOptimization(optimizedPrompt);
            }
            
            // Generate actual code using Ollama with optimization focus
            String optimizationContext = "You are a performance optimization expert. Generate optimized, efficient code. Focus on: parallel processing, memory efficiency, cache locality, algorithmic efficiency. " + context;
            String response = ollamaSpine.think(optimizedPrompt, optimizationContext);
            
            long thinkTime = System.currentTimeMillis() - startTime;
            totalThinkTime += thinkTime;
            
            System.out.println(">>> [OPENCLAW] Optimization completed in " + thinkTime + "ms");
            
            return response;
            
        } catch (Exception e) {
            System.err.println(">>> [OPENCLAW ERROR] " + e.getMessage());
            return generateOptimizedResponse(prompt, context); // Fallback to stub
        }
    }
    
    /**
     * Analyze prompt for optimization opportunities
     */
    private String analyzeForOptimization(String prompt) {
        // Add optimization hints
        if (prompt.toLowerCase().contains("optimize") || 
            prompt.toLowerCase().contains("performance") ||
            prompt.toLowerCase().contains("fast") ||
            prompt.toLowerCase().contains("efficient")) {
            return "// OPTIMIZED VERSION\n" + prompt;
        }
        return prompt;
    }
    
    /**
     * Apply FrayCL compute optimization
     */
    private String applyComputeOptimization(String prompt) {
        // In a full implementation, this would use FrayCL kernels
        // For now, just mark as compute-optimized
        return prompt + "\n// FrayCL compute optimization applied";
    }
    
    /**
     * Generate optimized response
     */
    private String generateOptimizedResponse(String prompt, String context) {
        StringBuilder response = new StringBuilder();
        
        response.append("// Generated by OpenClaw (Performance Optimized)\n");
        String taskDesc = prompt.replace("\n", " ").trim();
        if (taskDesc.length() > 50) {
            taskDesc = taskDesc.substring(0, 50);
        }
        response.append("// Task: ").append(taskDesc).append("...\n");
        if (!context.isEmpty()) {
            String contextDesc = context.trim();
            if (contextDesc.length() > 50) {
                contextDesc = contextDesc.substring(0, 50);
            }
            response.append("// Context: ").append(contextDesc).append("...\n");
        }
        response.append("\n");
        response.append("// Optimized code structure:\n");
        response.append("// - Parallel processing enabled\n");
        response.append("// - Memory efficiency optimized\n");
        response.append("// - Cache locality improved\n");
        response.append("\n");
        response.append("// TODO: Implement optimized version\n");
        
        return response.toString();
    }
    
    /**
     * Get model name
     */
    @Override
    public String getModel() {
        return model;
    }
    
    /**
     * Set active model (not supported for OpenClaw)
     */
    @Override
    public void setModel(String modelName) {
        System.out.println(">>> [OPENCLAW] Model switching not supported");
    }
    
    /**
     * Get available models
     */
    @Override
    public String[] getAvailableModels() {
        return new String[] { "openclaw-v1" };
    }
    
    /**
     * Test connection
     */
    @Override
    public boolean testConnection() {
        return computeContext != null;
    }
    
    /**
     * Get statistics
     */
    @Override
    public ModelStats getStats() {
        long avgTime = requestCount > 0 ? totalThinkTime / requestCount : 0;
        return new ModelStats(model, requestCount, avgTime, testConnection());
    }
    
    /**
     * Print statistics
     */
    public void printStats() {
        System.out.println("╔═══════════════════════════════════════════════════════════╗");
        System.out.println("║   OPENCLAW SPINE STATISTICS                              ║");
        System.out.println("╚═══════════════════════════════════════════════════════════╝");
        System.out.println("  Model: " + model);
        System.out.println("  Available: " + (testConnection() ? "Yes" : "No"));
        System.out.println("  Requests: " + requestCount);
        System.out.println("  Avg Think Time: " + (requestCount > 0 ? totalThinkTime / requestCount : 0) + "ms");
        System.out.println("  Total Think Time: " + totalThinkTime + "ms");
    }
}
