package fraymus.os;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

/**
 * FRAY PHI EXPLORER BUILDER
 *
 * Turns the Phi ideas exposed during Fraynix boot into a concrete, runnable
 * builder surface. The Java side is useful inside the live shell; the generated
 * C side is the same math distilled for the bare-metal image pipeline.
 */
public class FrayPhiExplorerBuilder {

    public static final double PHI = 1.618033988749895;
    public static final double PHI_INVERSE = 1.0 / PHI;
    public static final double PHI_SQUARED = PHI * PHI;
    public static final double GOLDEN_ANGLE_DEGREES = 360.0 * PHI_INVERSE * PHI_INVERSE;

    private static final String OUTPUT_DIR = "fraynix_src";

    public static void main(String[] args) {
        int terms = 12;
        if (args != null && args.length > 0) {
            try {
                terms = Integer.parseInt(args[0]);
            } catch (NumberFormatException ignored) {
                terms = 12;
            }
        }

        System.out.println("FRAY PHI EXPLORER BUILDER");
        System.out.println(describe(terms));

        try {
            Files.createDirectories(Path.of(OUTPUT_DIR));
            writeFile("phi_explorer.c", buildPhiExplorerC());
            writeFile("phi_explorer.md", buildPhiManifest());
            System.out.println("Phi explorer source generated in " + OUTPUT_DIR);
        } catch (IOException e) {
            System.err.println("Phi explorer build failed: " + e.getMessage());
        }
    }

    public static String describe(int requestedTerms) {
        int terms = Math.max(1, Math.min(requestedTerms, 24));
        long[] fibonacci = fibonacci(terms);

        StringBuilder out = new StringBuilder();
        out.append("phi=").append(format(PHI)).append('\n');
        out.append("phi^2=").append(format(PHI_SQUARED)).append('\n');
        out.append("1/phi=").append(format(PHI_INVERSE)).append('\n');
        out.append("golden_angle_degrees=").append(format(GOLDEN_ANGLE_DEGREES)).append('\n');
        out.append("fibonacci_terms=");
        for (int i = 0; i < fibonacci.length; i++) {
            if (i > 0) {
                out.append(", ");
            }
            out.append(fibonacci[i]);
        }
        out.append('\n');
        if (fibonacci.length >= 2 && fibonacci[fibonacci.length - 2] != 0) {
            double approximation = (double) fibonacci[fibonacci.length - 1] / fibonacci[fibonacci.length - 2];
            out.append("latest_ratio=").append(format(approximation)).append('\n');
            out.append("ratio_error=").append(format(Math.abs(PHI - approximation))).append('\n');
        }
        out.append("resonance(432Hz)=").append(format(resonanceScore(432.0))).append('\n');
        out.append("resonance(528Hz)=").append(format(resonanceScore(528.0))).append('\n');
        return out.toString();
    }

    public static long[] fibonacci(int requestedTerms) {
        int terms = Math.max(1, Math.min(requestedTerms, 92));
        long[] values = new long[terms];
        values[0] = 1;
        if (terms > 1) {
            values[1] = 1;
        }
        for (int i = 2; i < terms; i++) {
            values[i] = values[i - 1] + values[i - 2];
        }
        return values;
    }

    public static double phiPower(int exponent) {
        if (exponent == 0) {
            return 1.0;
        }
        double base = exponent > 0 ? PHI : PHI_INVERSE;
        int count = Math.abs(exponent);
        double value = 1.0;
        for (int i = 0; i < count; i++) {
            value *= base;
        }
        return value;
    }

    public static double resonanceScore(double value) {
        double phase = fractional(value / PHI);
        double distance = circularDistance(phase, PHI_INVERSE);
        return clamp(1.0 - distance * PHI, 0.0, 1.0);
    }

    public static double goldenAngleDegrees() {
        return GOLDEN_ANGLE_DEGREES;
    }

    private static double fractional(double value) {
        double floor = Math.floor(value);
        return value - floor;
    }

    private static double circularDistance(double a, double b) {
        double direct = Math.abs(a - b);
        return Math.min(direct, 1.0 - direct);
    }

    private static double clamp(double value, double min, double max) {
        return Math.max(min, Math.min(max, value));
    }

    private static String buildPhiExplorerC() {
        return """
/* FRAY PHI EXPLORER
 * Generated by FrayPhiExplorerBuilder.
 * Zero-dependency Phi math for the bare-metal Fraynix image.
 */

#ifndef FRAY_PHI_EXPLORER_C
#define FRAY_PHI_EXPLORER_C

#define FRAY_PHI 1.618033988749895
#define FRAY_PHI_INV 0.6180339887498948
#define FRAY_PHI_SQUARED 2.618033988749895
#define FRAY_GOLDEN_ANGLE_DEGREES 137.50776405003785

static double fray_abs(double x) {
    return x < 0.0 ? -x : x;
}

static double fray_floor(double x) {
    long whole = (long)x;
    if (x < 0.0 && (double)whole != x) {
        return (double)(whole - 1);
    }
    return (double)whole;
}

static double fray_fractional(double x) {
    return x - fray_floor(x);
}

double fray_phi_power(int exponent) {
    double base = exponent >= 0 ? FRAY_PHI : FRAY_PHI_INV;
    int count = exponent >= 0 ? exponent : -exponent;
    double value = 1.0;
    for (int i = 0; i < count; i++) {
        value *= base;
    }
    return value;
}

unsigned long fray_fibonacci(int n) {
    if (n <= 1) {
        return 1;
    }
    unsigned long a = 1;
    unsigned long b = 1;
    for (int i = 2; i <= n; i++) {
        unsigned long next = a + b;
        a = b;
        b = next;
    }
    return b;
}

double fray_phi_resonance(double value) {
    double phase = fray_fractional(value / FRAY_PHI);
    double direct = fray_abs(phase - FRAY_PHI_INV);
    double wrapped = 1.0 - direct;
    double distance = direct < wrapped ? direct : wrapped;
    double score = 1.0 - distance * FRAY_PHI;
    if (score < 0.0) return 0.0;
    if (score > 1.0) return 1.0;
    return score;
}

#endif
""";
    }

    private static String buildPhiManifest() {
        return """
# Fray Phi Explorer

Generated by `FrayPhiExplorerBuilder`.

Purpose:
- Expose Phi constants, Fibonacci ratios, golden-angle geometry, and resonance scoring as a runnable Fraynix builder.
- Provide `phi_explorer.c` for the bare-metal image pipeline.
- Give the HTML cockpit a concrete backend surface for Phi diagnostics instead of leaving Phi as startup narration only.

Shell:
- `phi`
- `phi 21`
- `builders run phi`
""";
    }

    private static void writeFile(String fileName, String content) throws IOException {
        Path path = Path.of(OUTPUT_DIR, fileName);
        Files.writeString(path, content, StandardCharsets.UTF_8);
        System.out.println("  -> " + path + " (" + content.length() + " bytes)");
    }

    private static String format(double value) {
        String text = String.format(Locale.ROOT, "%.12f", value);
        while (text.contains(".") && text.endsWith("0")) {
            text = text.substring(0, text.length() - 1);
        }
        if (text.endsWith(".")) {
            text = text.substring(0, text.length() - 1);
        }
        return text;
    }
}
