/* FRAY ALGEBRA SOLVER
 * Generated by FrayAlgebraSolverBuilder.
 * Linear and quadratic equation primitives for bare-metal Fraynix.
 */

#ifndef FRAY_ALGEBRA_SOLVER_C
#define FRAY_ALGEBRA_SOLVER_C

typedef struct {
    int has_solution;
    int infinite_solutions;
    double x;
} fray_linear_solution;

typedef struct {
    int complex_roots;
    double x1;
    double x2;
    double real;
    double imaginary;
    double discriminant;
} fray_quadratic_solution;

static double fray_abs_double(double x) {
    return x < 0.0 ? -x : x;
}

static double fray_sqrt(double x) {
    if (x <= 0.0) {
        return 0.0;
    }
    double guess = x > 1.0 ? x : 1.0;
    for (int i = 0; i < 32; i++) {
        guess = 0.5 * (guess + x / guess);
    }
    return guess;
}

fray_linear_solution fray_solve_linear(double a, double b) {
    fray_linear_solution out;
    out.has_solution = 1;
    out.infinite_solutions = 0;
    out.x = 0.0;

    if (fray_abs_double(a) < 0.000000001) {
        out.has_solution = fray_abs_double(b) < 0.000000001;
        out.infinite_solutions = out.has_solution;
        return out;
    }

    out.x = -b / a;
    return out;
}

fray_quadratic_solution fray_solve_quadratic(double a, double b, double c) {
    fray_quadratic_solution out;
    out.complex_roots = 0;
    out.x1 = 0.0;
    out.x2 = 0.0;
    out.real = 0.0;
    out.imaginary = 0.0;
    out.discriminant = b * b - 4.0 * a * c;

    if (out.discriminant >= 0.0) {
        double root = fray_sqrt(out.discriminant);
        out.x1 = (-b + root) / (2.0 * a);
        out.x2 = (-b - root) / (2.0 * a);
    } else {
        out.complex_roots = 1;
        out.real = -b / (2.0 * a);
        out.imaginary = fray_sqrt(-out.discriminant) / (2.0 * fray_abs_double(a));
    }
    return out;
}

#endif
