; FRAYNIX BOOTLOADER
; Multiboot-compliant for GRUB loading
; Generated by Fraymus - Gen 142

bits 32
section .text
    ; Multiboot header
    align 4
    dd 0x1BADB002              ; Magic number
    dd 0x00                    ; Flags
    dd -(0x1BADB002 + 0x00)    ; Checksum

global start
extern kmain

start:
    cli                        ; Disable interrupts
    mov esp, stack_space       ; Set up stack
    call kmain                 ; Call kernel
    hlt                        ; Halt if kernel returns

section .bss
resb 8192                      ; 8KB stack
stack_space:
