#!/bin/bash
# FRAYNIX BUILD SCRIPT
# Generated by Fraymus - Gen 142

set -e

echo "═══════════════════════════════════════════════════════════════"
echo "  FRAYNIX BUILD SYSTEM"
echo "═══════════════════════════════════════════════════════════════"

# Assemble bootloader
echo "[1/4] Assembling boot.asm..."
nasm -f elf32 boot.asm -o boot.o

# Compile kernel
echo "[2/4] Compiling kernel.c..."
i686-elf-gcc -c kernel.c -o kernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra

# Link
echo "[3/4] Linking..."
i686-elf-gcc -T linker.ld -o fraynix.bin -ffreestanding -O2 -nostdlib boot.o kernel.o -lgcc

# Create ISO
echo "[4/4] Creating ISO..."
mkdir -p isodir/boot/grub
cp fraynix.bin isodir/boot/fraynix.bin
cp grub.cfg isodir/boot/grub/grub.cfg
grub-mkrescue -o fraynix.iso isodir

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  ✅ BUILD COMPLETE: fraynix.iso"
echo "  Run: qemu-system-i386 -cdrom fraynix.iso"
echo "═══════════════════════════════════════════════════════════════"
