/* ═══════════════════════════════════════════════════════════════════════════
 * E1000 NETWORK DRIVER
 * Generated by Fraymus - Gen 146
 *
 * Virtual Intel E1000 NIC driver for QEMU/VirtualBox
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_E1000_C
#define FRAY_E1000_C

/* E1000 Register Offsets */
#define E1000_CTRL      0x0000
#define E1000_STATUS    0x0008
#define E1000_EERD      0x0014
#define E1000_ICR       0x00C0
#define E1000_IMS       0x00D0
#define E1000_IMC       0x00D8
#define E1000_RCTL      0x0100
#define E1000_TCTL      0x0400
#define E1000_RDBAL     0x2800
#define E1000_RDBAH     0x2804
#define E1000_RDLEN     0x2808
#define E1000_RDH       0x2810
#define E1000_RDT       0x2818
#define E1000_TDBAL     0x3800
#define E1000_TDBAH     0x3804
#define E1000_TDLEN     0x3808
#define E1000_TDH       0x3810
#define E1000_TDT       0x3818

/* Transmit Descriptor */
typedef struct __attribute__((packed)) {
    unsigned long long addr;
    unsigned short length;
    unsigned char cso;
    unsigned char cmd;
    unsigned char sta;
    unsigned char css;
    unsigned short special;
} E1000TxDesc;

/* Receive Descriptor */
typedef struct __attribute__((packed)) {
    unsigned long long addr;
    unsigned short length;
    unsigned short checksum;
    unsigned char status;
    unsigned char errors;
    unsigned short special;
} E1000RxDesc;

#define TX_DESC_COUNT 32
#define RX_DESC_COUNT 32

static E1000TxDesc tx_descs[TX_DESC_COUNT] __attribute__((aligned(16)));
static E1000RxDesc rx_descs[RX_DESC_COUNT] __attribute__((aligned(16)));
static unsigned char tx_buffers[TX_DESC_COUNT][2048] __attribute__((aligned(16)));
static unsigned char rx_buffers[RX_DESC_COUNT][2048] __attribute__((aligned(16)));

static unsigned int e1000_base = 0;  /* MMIO base address */
static int tx_cur = 0;
static int rx_cur = 0;

/* Read/Write E1000 registers */
static inline void e1000_write(unsigned int reg, unsigned int val) {
    *(volatile unsigned int*)(e1000_base + reg) = val;
}

static inline unsigned int e1000_read(unsigned int reg) {
    return *(volatile unsigned int*)(e1000_base + reg);
}

void e1000_init(void) {
    /* In a real driver, we would:
     * 1. Scan PCI for E1000 device (vendor 0x8086, device 0x100E)
     * 2. Map MMIO registers
     * 3. Reset the device
     * 4. Set up TX/RX descriptor rings
     * 5. Enable interrupts
     *
     * For simulation, we assume e1000_base is pre-configured
     */

    /* Initialize TX descriptors */
    for (int i = 0; i < TX_DESC_COUNT; i++) {
        tx_descs[i].addr = (unsigned long long)(unsigned int)tx_buffers[i];
        tx_descs[i].cmd = 0;
        tx_descs[i].sta = 1;  /* DD (Descriptor Done) */
    }

    /* Initialize RX descriptors */
    for (int i = 0; i < RX_DESC_COUNT; i++) {
        rx_descs[i].addr = (unsigned long long)(unsigned int)rx_buffers[i];
        rx_descs[i].status = 0;
    }

    kprint("  E1000 NIC initialized\n");
}

void e1000_transmit(unsigned char* data, int len) {
    if (len > 1518) len = 1518;

    /* Wait for descriptor to be available */
    while (!(tx_descs[tx_cur].sta & 1)) {
        /* Busy wait - in real driver, use interrupts */
    }

    /* Copy data to buffer */
    for (int i = 0; i < len; i++) {
        tx_buffers[tx_cur][i] = data[i];
    }

    /* Set up descriptor */
    tx_descs[tx_cur].length = len;
    tx_descs[tx_cur].cmd = 0x0B;  /* EOP | IFCS | RS */
    tx_descs[tx_cur].sta = 0;

    /* Notify hardware */
    int old_cur = tx_cur;
    tx_cur = (tx_cur + 1) % TX_DESC_COUNT;

    /* In real driver: e1000_write(E1000_TDT, tx_cur); */

    /* Simulate immediate completion */
    tx_descs[old_cur].sta = 1;

    kprint_color(" [NET] TX: ", 0x0A);
    kprint_int(len);
    kprint(" bytes\n");
}

int e1000_receive(unsigned char* buffer, int max_len) {
    /* Check if packet available */
    if (!(rx_descs[rx_cur].status & 1)) {
        return 0;  /* No packet */
    }

    int len = rx_descs[rx_cur].length;
    if (len > max_len) len = max_len;

    /* Copy data */
    for (int i = 0; i < len; i++) {
        buffer[i] = rx_buffers[rx_cur][i];
    }

    /* Reset descriptor */
    rx_descs[rx_cur].status = 0;
    rx_cur = (rx_cur + 1) % RX_DESC_COUNT;

    /* In real driver: e1000_write(E1000_RDT, rx_cur); */

    return len;
}

#endif /* FRAY_E1000_C */
