/* ═══════════════════════════════════════════════════════════════════════════
 * FRAY-GPU: SOFTWARE 3D RASTERIZER
 * Generated by Fraymus - Gen 145
 *
 * Complete 3D rendering pipeline in pure C
 *
 * Pipeline:
 *   1. Model Space → World Space (transform)
 *   2. World Space → Camera Space (view)
 *   3. Camera Space → Clip Space (projection)
 *   4. Clip Space → Screen Space (viewport)
 *   5. Rasterization (draw pixels)
 *
 * "The CPU becomes the GPU."
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_GPU_C
#define FRAY_GPU_C

#include "math3d.c"

/* Screen dimensions (Mode 13h) */
#define GPU_WIDTH  320
#define GPU_HEIGHT 200

/* Camera settings */
#define GPU_FOV         128   /* Field of view scale */
#define GPU_NEAR        FP_ONE
#define GPU_FAR         INT_TO_FP(100)
#define GPU_DISTANCE    INT_TO_FP(5)  /* Camera distance from origin */

/* Z-buffer */
static int zbuffer[GPU_WIDTH * GPU_HEIGHT];

/* Frame counter */
static unsigned int gpu_frame = 0;

/* ═══════════════════════════════════════════════════════════════════════════
 * PROJECTION
 * ═══════════════════════════════════════════════════════════════════════════ */

Point2D gpu_project(Vec3 p) {
    Point2D screen;

    /* Translate away from camera */
    int z = p.z + GPU_DISTANCE;

    /* Prevent divide by zero */
    if (z < FP_ONE) z = FP_ONE;

    /* Perspective divide */
    screen.x = FP_DIV(FP_MUL(p.x, INT_TO_FP(GPU_FOV)), z) + (GPU_WIDTH / 2);
    screen.y = FP_DIV(FP_MUL(p.y, INT_TO_FP(GPU_FOV)), z) + (GPU_HEIGHT / 2);

    return screen;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Z-BUFFER
 * ═══════════════════════════════════════════════════════════════════════════ */

void gpu_clear_zbuffer(void) {
    for (int i = 0; i < GPU_WIDTH * GPU_HEIGHT; i++) {
        zbuffer[i] = 0x7FFFFFFF;  /* Max int */
    }
}

int gpu_test_z(int x, int y, int z) {
    if (x < 0 || x >= GPU_WIDTH || y < 0 || y >= GPU_HEIGHT) return 0;
    int idx = y * GPU_WIDTH + x;
    if (z < zbuffer[idx]) {
        zbuffer[idx] = z;
        return 1;
    }
    return 0;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * DRAWING PRIMITIVES
 * ═══════════════════════════════════════════════════════════════════════════ */

void gpu_draw_line_3d(Vec3 a, Vec3 b, unsigned char color) {
    Point2D p1 = gpu_project(a);
    Point2D p2 = gpu_project(b);

    /* Bresenham's line */
    int dx = p2.x - p1.x;
    int dy = p2.y - p1.y;
    int sx = dx > 0 ? 1 : -1;
    int sy = dy > 0 ? 1 : -1;
    dx = dx < 0 ? -dx : dx;
    dy = dy < 0 ? -dy : dy;

    int err = (dx > dy ? dx : -dy) / 2;
    int x = p1.x, y = p1.y;

    while (1) {
        vga_put_pixel(x, y, color);
        if (x == p2.x && y == p2.y) break;
        int e2 = err;
        if (e2 > -dx) { err -= dy; x += sx; }
        if (e2 < dy)  { err += dx; y += sy; }
    }
}

void gpu_draw_triangle_wire(Vec3 a, Vec3 b, Vec3 c, unsigned char color) {
    gpu_draw_line_3d(a, b, color);
    gpu_draw_line_3d(b, c, color);
    gpu_draw_line_3d(c, a, color);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * MESH RENDERING
 * ═══════════════════════════════════════════════════════════════════════════ */

typedef struct {
    Vec3* vertices;
    int vertex_count;
    int* indices;      /* Triangles: v0, v1, v2, v0, v1, v2, ... */
    int index_count;
    unsigned char color;
} Mesh;

void gpu_draw_mesh(Mesh* mesh, Mat3* rotation, Vec3 position) {
    /* Transform and project all vertices */
    Point2D* projected = (Point2D*)kmalloc(mesh->vertex_count * sizeof(Point2D));
    Vec3* transformed = (Vec3*)kmalloc(mesh->vertex_count * sizeof(Vec3));

    for (int i = 0; i < mesh->vertex_count; i++) {
        /* Rotate */
        transformed[i] = mat3_mul_vec(rotation, mesh->vertices[i]);
        /* Translate */
        transformed[i] = vec3_add(transformed[i], position);
        /* Project */
        projected[i] = gpu_project(transformed[i]);
    }

    /* Draw wireframe triangles */
    for (int i = 0; i < mesh->index_count; i += 3) {
        int i0 = mesh->indices[i];
        int i1 = mesh->indices[i + 1];
        int i2 = mesh->indices[i + 2];

        gpu_draw_triangle_wire(
            transformed[i0],
            transformed[i1],
            transformed[i2],
            mesh->color
        );
    }

    kfree(projected);
    kfree(transformed);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * CUBE MESH
 * ═══════════════════════════════════════════════════════════════════════════ */

static Vec3 cube_vertices[8] = {
    { -FP_ONE, -FP_ONE, -FP_ONE },
    {  FP_ONE, -FP_ONE, -FP_ONE },
    {  FP_ONE,  FP_ONE, -FP_ONE },
    { -FP_ONE,  FP_ONE, -FP_ONE },
    { -FP_ONE, -FP_ONE,  FP_ONE },
    {  FP_ONE, -FP_ONE,  FP_ONE },
    {  FP_ONE,  FP_ONE,  FP_ONE },
    { -FP_ONE,  FP_ONE,  FP_ONE }
};

static int cube_indices[36] = {
    /* Front */  0, 1, 2, 0, 2, 3,
    /* Back */   4, 6, 5, 4, 7, 6,
    /* Left */   0, 3, 7, 0, 7, 4,
    /* Right */  1, 5, 6, 1, 6, 2,
    /* Top */    3, 2, 6, 3, 6, 7,
    /* Bottom */ 0, 4, 5, 0, 5, 1
};

static Mesh cube_mesh = {
    cube_vertices, 8,
    cube_indices, 36,
    14  /* Yellow */
};

/* ═══════════════════════════════════════════════════════════════════════════
 * DEMO: SPINNING CUBE
 * ═══════════════════════════════════════════════════════════════════════════ */

void gpu_demo_frame(void) {
    gpu_frame++;

    /* Clear screen */
    vga_clear(0);
    gpu_clear_zbuffer();

    /* Create rotation matrix */
    Mat3 rot_y, rot_x, rot;
    mat3_rot_y(&rot_y, gpu_frame);
    mat3_rot_x(&rot_x, gpu_frame / 2);

    /* Combine rotations (simplified) */
    rot = rot_y;  /* For demo, just Y rotation */

    /* Position */
    Vec3 pos = { 0, 0, 0 };

    /* Draw cube */
    gpu_draw_mesh(&cube_mesh, &rot, pos);

    /* Draw axes */
    Vec3 origin = { 0, 0, 0 };
    Vec3 x_axis = { INT_TO_FP(2), 0, 0 };
    Vec3 y_axis = { 0, INT_TO_FP(2), 0 };
    Vec3 z_axis = { 0, 0, INT_TO_FP(2) };

    gpu_draw_line_3d(origin, x_axis, 4);   /* Red = X */
    gpu_draw_line_3d(origin, y_axis, 2);   /* Green = Y */
    gpu_draw_line_3d(origin, z_axis, 1);   /* Blue = Z */

    /* Frame counter */
    vga_put_pixel(5, 5, 15);  /* Activity indicator */
}

void gpu_run_demo(void) {
    vga_init();
    vga_init_palette();
    init_heap();

    while (1) {
        gpu_demo_frame();
        vga_wait_vsync();
    }
}

#endif /* FRAY_GPU_C */
