/* ═══════════════════════════════════════════════════════════════════════════
 * FRAY-HEAP: DYNAMIC MEMORY ALLOCATOR
 * Generated by Fraymus - Gen 145
 *
 * Simple first-fit allocator with coalescing
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_HEAP_C
#define FRAY_HEAP_C

#define HEAP_START 0x00400000  /* 4MB mark */
#define HEAP_SIZE  0x00400000  /* 4MB heap */

typedef struct block_header {
    unsigned int size;
    unsigned int is_free;
    struct block_header* next;
} block_header_t;

static block_header_t* heap_start = 0;
static unsigned int heap_end = 0;

void init_heap(void) {
    heap_start = (block_header_t*)HEAP_START;
    heap_start->size = HEAP_SIZE - sizeof(block_header_t);
    heap_start->is_free = 1;
    heap_start->next = 0;
    heap_end = HEAP_START + HEAP_SIZE;
}

void* kmalloc(unsigned int size) {
    /* Align to 4 bytes */
    size = (size + 3) & ~3;

    block_header_t* current = heap_start;

    while (current) {
        if (current->is_free && current->size >= size) {
            /* Split block if large enough */
            if (current->size > size + sizeof(block_header_t) + 16) {
                block_header_t* new_block = (block_header_t*)((char*)current + sizeof(block_header_t) + size);
                new_block->size = current->size - size - sizeof(block_header_t);
                new_block->is_free = 1;
                new_block->next = current->next;

                current->size = size;
                current->next = new_block;
            }

            current->is_free = 0;
            return (void*)((char*)current + sizeof(block_header_t));
        }
        current = current->next;
    }

    return 0;  /* Out of memory */
}

void kfree(void* ptr) {
    if (!ptr) return;

    block_header_t* header = (block_header_t*)((char*)ptr - sizeof(block_header_t));
    header->is_free = 1;

    /* Coalesce with next block if free */
    if (header->next && header->next->is_free) {
        header->size += sizeof(block_header_t) + header->next->size;
        header->next = header->next->next;
    }
}

void* krealloc(void* ptr, unsigned int size) {
    if (!ptr) return kmalloc(size);

    block_header_t* header = (block_header_t*)((char*)ptr - sizeof(block_header_t));

    if (header->size >= size) return ptr;

    void* new_ptr = kmalloc(size);
    if (new_ptr) {
        /* Copy old data */
        char* src = (char*)ptr;
        char* dst = (char*)new_ptr;
        for (unsigned int i = 0; i < header->size; i++) {
            dst[i] = src[i];
        }
        kfree(ptr);
    }
    return new_ptr;
}

#endif /* FRAY_HEAP_C */
