/* ═══════════════════════════════════════════════════════════════════════════
 * FRAY-MATH: 3D MATHEMATICS LIBRARY
 * Generated by Fraymus - Gen 145
 *
 * Fixed-point arithmetic for FPU-less systems
 * All values scaled by 256 (8.8 fixed point)
 *
 * "Pure math needs no hardware."
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_MATH3D_C
#define FRAY_MATH3D_C

/* Fixed-point scale factor */
#define FP_SHIFT 8
#define FP_ONE   (1 << FP_SHIFT)  /* 256 */
#define FP_HALF  (FP_ONE >> 1)     /* 128 */

/* Convert int to fixed-point */
#define INT_TO_FP(x) ((x) << FP_SHIFT)
#define FP_TO_INT(x) ((x) >> FP_SHIFT)

/* Fixed-point multiply */
#define FP_MUL(a, b) (((a) * (b)) >> FP_SHIFT)

/* Fixed-point divide */
#define FP_DIV(a, b) (((a) << FP_SHIFT) / (b))

/* ═══════════════════════════════════════════════════════════════════════════
 * TRIGONOMETRY LOOKUP TABLES
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Sin table: 256 entries for 0-360 degrees, scaled by 256 */
static const int sin_table[256] = {
    0, 6, 12, 18, 25, 31, 37, 43, 49, 56, 62, 68, 74, 80, 86, 92,
    97, 103, 109, 115, 120, 126, 131, 136, 142, 147, 152, 157, 162, 167, 171, 176,
    180, 185, 189, 193, 197, 201, 205, 209, 212, 216, 219, 222, 225, 228, 231, 233,
    236, 238, 240, 242, 244, 246, 247, 249, 250, 251, 252, 253, 254, 254, 255, 255,
    256, 255, 255, 254, 254, 253, 252, 251, 250, 249, 247, 246, 244, 242, 240, 238,
    236, 233, 231, 228, 225, 222, 219, 216, 212, 209, 205, 201, 197, 193, 189, 185,
    180, 176, 171, 167, 162, 157, 152, 147, 142, 136, 131, 126, 120, 115, 109, 103,
    97, 92, 86, 80, 74, 68, 62, 56, 49, 43, 37, 31, 25, 18, 12, 6,
    0, -6, -12, -18, -25, -31, -37, -43, -49, -56, -62, -68, -74, -80, -86, -92,
    -97, -103, -109, -115, -120, -126, -131, -136, -142, -147, -152, -157, -162, -167, -171, -176,
    -180, -185, -189, -193, -197, -201, -205, -209, -212, -216, -219, -222, -225, -228, -231, -233,
    -236, -238, -240, -242, -244, -246, -247, -249, -250, -251, -252, -253, -254, -254, -255, -255,
    -256, -255, -255, -254, -254, -253, -252, -251, -250, -249, -247, -246, -244, -242, -240, -238,
    -236, -233, -231, -228, -225, -222, -219, -216, -212, -209, -205, -201, -197, -193, -189, -185,
    -180, -176, -171, -167, -162, -157, -152, -147, -142, -136, -131, -126, -120, -115, -109, -103,
    -97, -92, -86, -80, -74, -68, -62, -56, -49, -43, -37, -31, -25, -18, -12, -6
};

static inline int fp_sin(int angle) {
    return sin_table[angle & 0xFF];
}

static inline int fp_cos(int angle) {
    return sin_table[(angle + 64) & 0xFF];
}

/* ═══════════════════════════════════════════════════════════════════════════
 * VECTOR TYPES
 * ═══════════════════════════════════════════════════════════════════════════ */

typedef struct {
    int x, y, z;  /* Fixed-point */
} Vec3;

typedef struct {
    int x, y;     /* Screen coordinates */
} Point2D;

typedef struct {
    int m[3][3];  /* 3x3 rotation matrix, fixed-point */
} Mat3;

/* ═══════════════════════════════════════════════════════════════════════════
 * VECTOR OPERATIONS
 * ═══════════════════════════════════════════════════════════════════════════ */

static inline Vec3 vec3_add(Vec3 a, Vec3 b) {
    Vec3 r = { a.x + b.x, a.y + b.y, a.z + b.z };
    return r;
}

static inline Vec3 vec3_sub(Vec3 a, Vec3 b) {
    Vec3 r = { a.x - b.x, a.y - b.y, a.z - b.z };
    return r;
}

static inline Vec3 vec3_scale(Vec3 v, int s) {
    Vec3 r = { FP_MUL(v.x, s), FP_MUL(v.y, s), FP_MUL(v.z, s) };
    return r;
}

static inline int vec3_dot(Vec3 a, Vec3 b) {
    return FP_MUL(a.x, b.x) + FP_MUL(a.y, b.y) + FP_MUL(a.z, b.z);
}

static inline Vec3 vec3_cross(Vec3 a, Vec3 b) {
    Vec3 r;
    r.x = FP_MUL(a.y, b.z) - FP_MUL(a.z, b.y);
    r.y = FP_MUL(a.z, b.x) - FP_MUL(a.x, b.z);
    r.z = FP_MUL(a.x, b.y) - FP_MUL(a.y, b.x);
    return r;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * MATRIX OPERATIONS
 * ═══════════════════════════════════════════════════════════════════════════ */

static inline Vec3 mat3_mul_vec(Mat3* m, Vec3 v) {
    Vec3 r;
    r.x = FP_MUL(m->m[0][0], v.x) + FP_MUL(m->m[0][1], v.y) + FP_MUL(m->m[0][2], v.z);
    r.y = FP_MUL(m->m[1][0], v.x) + FP_MUL(m->m[1][1], v.y) + FP_MUL(m->m[1][2], v.z);
    r.z = FP_MUL(m->m[2][0], v.x) + FP_MUL(m->m[2][1], v.y) + FP_MUL(m->m[2][2], v.z);
    return r;
}

/* Rotation around X axis */
void mat3_rot_x(Mat3* m, int angle) {
    int c = fp_cos(angle);
    int s = fp_sin(angle);
    m->m[0][0] = FP_ONE; m->m[0][1] = 0;  m->m[0][2] = 0;
    m->m[1][0] = 0;      m->m[1][1] = c;  m->m[1][2] = -s;
    m->m[2][0] = 0;      m->m[2][1] = s;  m->m[2][2] = c;
}

/* Rotation around Y axis */
void mat3_rot_y(Mat3* m, int angle) {
    int c = fp_cos(angle);
    int s = fp_sin(angle);
    m->m[0][0] = c;  m->m[0][1] = 0;      m->m[0][2] = s;
    m->m[1][0] = 0;  m->m[1][1] = FP_ONE; m->m[1][2] = 0;
    m->m[2][0] = -s; m->m[2][1] = 0;      m->m[2][2] = c;
}

/* Rotation around Z axis */
void mat3_rot_z(Mat3* m, int angle) {
    int c = fp_cos(angle);
    int s = fp_sin(angle);
    m->m[0][0] = c;  m->m[0][1] = -s; m->m[0][2] = 0;
    m->m[1][0] = s;  m->m[1][1] = c;  m->m[1][2] = 0;
    m->m[2][0] = 0;  m->m[2][1] = 0;  m->m[2][2] = FP_ONE;
}

#endif /* FRAY_MATH3D_C */
