/* ═══════════════════════════════════════════════════════════════════════════
 * FRAY-MESHES: 3D MODEL DATA
 * Generated by Fraymus - Gen 145
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_MESHES_C
#define FRAY_MESHES_C

/* ═══════════════════════════════════════════════════════════════════════════
 * PYRAMID (4 vertices, 6 triangles)
 * ═══════════════════════════════════════════════════════════════════════════ */

static Vec3 pyramid_vertices[5] = {
    { 0,           INT_TO_FP(1), 0 },            /* Top */
    { -FP_ONE,    -FP_ONE,      -FP_ONE },       /* Base corners */
    {  FP_ONE,    -FP_ONE,      -FP_ONE },
    {  FP_ONE,    -FP_ONE,       FP_ONE },
    { -FP_ONE,    -FP_ONE,       FP_ONE }
};

static int pyramid_indices[18] = {
    0, 1, 2,  /* Front face */
    0, 2, 3,  /* Right face */
    0, 3, 4,  /* Back face */
    0, 4, 1,  /* Left face */
    1, 3, 2,  /* Base triangle 1 */
    1, 4, 3   /* Base triangle 2 */
};

static Mesh pyramid_mesh = {
    pyramid_vertices, 5,
    pyramid_indices, 18,
    10  /* Light green */
};

/* ═══════════════════════════════════════════════════════════════════════════
 * PHI RECTANGLE (Golden ratio proportions)
 * ═══════════════════════════════════════════════════════════════════════════ */

#define PHI_SCALE 414  /* 1.618 * 256 ≈ 414 */

static Vec3 phi_rect_vertices[4] = {
    { -PHI_SCALE, -FP_ONE, 0 },
    {  PHI_SCALE, -FP_ONE, 0 },
    {  PHI_SCALE,  FP_ONE, 0 },
    { -PHI_SCALE,  FP_ONE, 0 }
};

static int phi_rect_indices[6] = {
    0, 1, 2,
    0, 2, 3
};

static Mesh phi_rect_mesh = {
    phi_rect_vertices, 4,
    phi_rect_indices, 6,
    6  /* Brown/Gold */
};

#endif /* FRAY_MESHES_C */
