/* ═══════════════════════════════════════════════════════════════════════════
 * FRAY-NET: BARE METAL NETWORK STACK
 * Generated by Fraymus - Gen 146
 *
 * Protocols:
 *   - Ethernet II (Layer 2)
 *   - ARP (Address Resolution)
 *   - IPv4 (Layer 3)
 *   - UDP (Layer 4)
 *
 * "Raw packets. No kernel overhead. Pure speed."
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_NET_C
#define FRAY_NET_C

/* ═══════════════════════════════════════════════════════════════════════════
 * NETWORK CONFIGURATION
 * ═══════════════════════════════════════════════════════════════════════════ */

static unsigned char my_mac[6] = { 0x52, 0x54, 0x00, 0x12, 0x34, 0x56 };
static unsigned char my_ip[4] = { 192, 168, 1, 100 };
static unsigned char gateway_ip[4] = { 192, 168, 1, 1 };
static unsigned char broadcast_mac[6] = { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF };

/* Game server */
static unsigned char server_ip[4] = { 192, 168, 1, 1 };
static unsigned short game_port = 7777;

/* ═══════════════════════════════════════════════════════════════════════════
 * PACKET STRUCTURES
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Ethernet Header (14 bytes) */
typedef struct __attribute__((packed)) {
    unsigned char dest_mac[6];
    unsigned char src_mac[6];
    unsigned short ethertype;  /* 0x0800 = IP, 0x0806 = ARP */
} EthernetHeader;

/* IPv4 Header (20 bytes minimum) */
typedef struct __attribute__((packed)) {
    unsigned char version_ihl;      /* Version (4) + IHL (5) = 0x45 */
    unsigned char tos;              /* Type of Service */
    unsigned short total_length;    /* Total packet length */
    unsigned short id;              /* Identification */
    unsigned short flags_fragment;  /* Flags + Fragment offset */
    unsigned char ttl;              /* Time to Live */
    unsigned char protocol;         /* 17 = UDP, 6 = TCP */
    unsigned short checksum;        /* Header checksum */
    unsigned char src_ip[4];
    unsigned char dest_ip[4];
} IPHeader;

/* UDP Header (8 bytes) */
typedef struct __attribute__((packed)) {
    unsigned short src_port;
    unsigned short dest_port;
    unsigned short length;
    unsigned short checksum;
} UDPHeader;

/* ARP Packet */
typedef struct __attribute__((packed)) {
    unsigned short hw_type;         /* 1 = Ethernet */
    unsigned short proto_type;      /* 0x0800 = IP */
    unsigned char hw_size;          /* 6 for MAC */
    unsigned char proto_size;       /* 4 for IP */
    unsigned short opcode;          /* 1 = Request, 2 = Reply */
    unsigned char sender_mac[6];
    unsigned char sender_ip[4];
    unsigned char target_mac[6];
    unsigned char target_ip[4];
} ARPPacket;

/* Game Packet Payload */
typedef struct __attribute__((packed)) {
    char magic[4];          /* "FRAY" */
    unsigned char type;     /* 0=Position, 1=Chat, 2=Event */
    unsigned short player_id;
    int pos_x;
    int pos_y;
    int pos_z;
    int dir_angle;
    unsigned char health;
    unsigned char ammo;
} GamePacket;

/* ═══════════════════════════════════════════════════════════════════════════
 * PACKET BUFFERS
 * ═══════════════════════════════════════════════════════════════════════════ */

#define MAX_PACKET_SIZE 1518
#define RX_BUFFER_SIZE  16
#define TX_BUFFER_SIZE  16

static unsigned char tx_buffer[TX_BUFFER_SIZE][MAX_PACKET_SIZE];
static unsigned char rx_buffer[RX_BUFFER_SIZE][MAX_PACKET_SIZE];
static int tx_head = 0, tx_tail = 0;
static int rx_head = 0, rx_tail = 0;

/* Statistics */
static unsigned int packets_sent = 0;
static unsigned int packets_received = 0;
static unsigned int packets_dropped = 0;

/* ═══════════════════════════════════════════════════════════════════════════
 * CHECKSUM CALCULATION
 * ═══════════════════════════════════════════════════════════════════════════ */

static unsigned short ip_checksum(void* data, int len) {
    unsigned int sum = 0;
    unsigned short* ptr = (unsigned short*)data;

    while (len > 1) {
        sum += *ptr++;
        len -= 2;
    }

    if (len == 1) {
        sum += *(unsigned char*)ptr;
    }

    while (sum >> 16) {
        sum = (sum & 0xFFFF) + (sum >> 16);
    }

    return ~sum;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * BYTE ORDER CONVERSION (Network = Big Endian)
 * ═══════════════════════════════════════════════════════════════════════════ */

static inline unsigned short htons(unsigned short h) {
    return ((h & 0xFF) << 8) | ((h >> 8) & 0xFF);
}

static inline unsigned short ntohs(unsigned short n) {
    return htons(n);
}

static inline unsigned int htonl(unsigned int h) {
    return ((h & 0xFF) << 24) | ((h & 0xFF00) << 8) |
           ((h >> 8) & 0xFF00) | ((h >> 24) & 0xFF);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * PACKET CONSTRUCTION
 * ═══════════════════════════════════════════════════════════════════════════ */

int net_build_udp_packet(unsigned char* buffer,
                         unsigned char* dest_mac,
                         unsigned char* dest_ip,
                         unsigned short dest_port,
                         unsigned char* payload,
                         int payload_len) {

    int offset = 0;

    /* Ethernet Header */
    EthernetHeader* eth = (EthernetHeader*)buffer;
    for (int i = 0; i < 6; i++) {
        eth->dest_mac[i] = dest_mac[i];
        eth->src_mac[i] = my_mac[i];
    }
    eth->ethertype = htons(0x0800);  /* IP */
    offset += sizeof(EthernetHeader);

    /* IP Header */
    IPHeader* ip = (IPHeader*)(buffer + offset);
    ip->version_ihl = 0x45;  /* IPv4, 5 words */
    ip->tos = 0;
    ip->total_length = htons(sizeof(IPHeader) + sizeof(UDPHeader) + payload_len);
    ip->id = htons(packets_sent);
    ip->flags_fragment = 0;
    ip->ttl = 64;
    ip->protocol = 17;  /* UDP */
    ip->checksum = 0;
    for (int i = 0; i < 4; i++) {
        ip->src_ip[i] = my_ip[i];
        ip->dest_ip[i] = dest_ip[i];
    }
    ip->checksum = ip_checksum(ip, sizeof(IPHeader));
    offset += sizeof(IPHeader);

    /* UDP Header */
    UDPHeader* udp = (UDPHeader*)(buffer + offset);
    udp->src_port = htons(game_port);
    udp->dest_port = htons(dest_port);
    udp->length = htons(sizeof(UDPHeader) + payload_len);
    udp->checksum = 0;  /* Optional for UDP */
    offset += sizeof(UDPHeader);

    /* Payload */
    for (int i = 0; i < payload_len; i++) {
        buffer[offset + i] = payload[i];
    }
    offset += payload_len;

    return offset;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * GAME NETWORKING
 * ═══════════════════════════════════════════════════════════════════════════ */

void net_broadcast_position(int x, int y, int z, int angle) {
    GamePacket game;
    game.magic[0] = 'F';
    game.magic[1] = 'R';
    game.magic[2] = 'A';
    game.magic[3] = 'Y';
    game.type = 0;  /* Position update */
    game.player_id = 1;
    game.pos_x = x;
    game.pos_y = y;
    game.pos_z = z;
    game.dir_angle = angle;
    game.health = 100;
    game.ammo = 50;

    unsigned char packet[MAX_PACKET_SIZE];
    int len = net_build_udp_packet(packet, broadcast_mac, server_ip,
                                   game_port, (unsigned char*)&game, sizeof(GamePacket));

    e1000_transmit(packet, len);
    packets_sent++;
}

void net_send_chat(const char* message) {
    unsigned char payload[256];
    payload[0] = 'F'; payload[1] = 'R'; payload[2] = 'A'; payload[3] = 'Y';
    payload[4] = 1;  /* Chat type */

    int i = 0;
    while (message[i] && i < 250) {
        payload[5 + i] = message[i];
        i++;
    }
    payload[5 + i] = 0;

    unsigned char packet[MAX_PACKET_SIZE];
    int len = net_build_udp_packet(packet, broadcast_mac, server_ip,
                                   game_port, payload, 6 + i);

    e1000_transmit(packet, len);
    packets_sent++;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * PACKET RECEPTION
 * ═══════════════════════════════════════════════════════════════════════════ */

void net_process_packet(unsigned char* packet, int len) {
    EthernetHeader* eth = (EthernetHeader*)packet;

    /* Check if packet is for us or broadcast */
    int for_us = 1;
    for (int i = 0; i < 6; i++) {
        if (eth->dest_mac[i] != my_mac[i] && eth->dest_mac[i] != 0xFF) {
            for_us = 0;
            break;
        }
    }
    if (!for_us) return;

    unsigned short ethertype = ntohs(eth->ethertype);

    if (ethertype == 0x0800) {
        /* IP Packet */
        IPHeader* ip = (IPHeader*)(packet + sizeof(EthernetHeader));

        if (ip->protocol == 17) {
            /* UDP */
            UDPHeader* udp = (UDPHeader*)(packet + sizeof(EthernetHeader) + sizeof(IPHeader));
            unsigned char* payload = packet + sizeof(EthernetHeader) + sizeof(IPHeader) + sizeof(UDPHeader);

            /* Check for game packet */
            if (payload[0] == 'F' && payload[1] == 'R' &&
                payload[2] == 'A' && payload[3] == 'Y') {
                GamePacket* game = (GamePacket*)payload;

                /* Handle game packet based on type */
                if (game->type == 0) {
                    /* Position update from another player */
                    kprint("[NET] Player ");
                    kprint_int(game->player_id);
                    kprint(" at (");
                    kprint_int(game->pos_x);
                    kprint(",");
                    kprint_int(game->pos_y);
                    kprint(")\n");
                }
            }
        }
    } else if (ethertype == 0x0806) {
        /* ARP - respond to requests for our IP */
        /* (Implementation omitted for brevity) */
    }

    packets_received++;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * INITIALIZATION
 * ═══════════════════════════════════════════════════════════════════════════ */

void net_init(void) {
    kprint_color("\n  FRAY-NET INITIALIZING...\n", 0x0A);

    e1000_init();

    kprint("  MAC: ");
    for (int i = 0; i < 6; i++) {
        if (i > 0) kprint(":");
        kprint_hex(my_mac[i]);
    }
    kprint("\n");

    kprint("  IP:  ");
    for (int i = 0; i < 4; i++) {
        if (i > 0) kprint(".");
        kprint_int(my_ip[i]);
    }
    kprint("\n");

    kprint_color("  NETWORK ONLINE\n\n", 0x0A);
}

void net_status(void) {
    kprint_color("\n  NETWORK STATUS\n", 0x0B);
    kprint("  ────────────────────────────\n");
    kprint("  Packets sent:     ");
    kprint_int(packets_sent);
    kprint("\n");
    kprint("  Packets received: ");
    kprint_int(packets_received);
    kprint("\n");
    kprint("  Packets dropped:  ");
    kprint_int(packets_dropped);
    kprint("\n\n");
}

#endif /* FRAY_NET_C */
