; ═══════════════════════════════════════════════════════════════════════════
; FRAY-MEM: PAGING ASSEMBLY ROUTINES
; Generated by Fraymus - Gen 145
; ═══════════════════════════════════════════════════════════════════════════

bits 32
section .text

global load_page_directory
global enable_paging
global flush_tlb
global get_faulting_address

; Load page directory address into CR3
load_page_directory:
    push ebp
    mov ebp, esp
    mov eax, [ebp + 8]    ; Get pointer argument
    mov cr3, eax          ; Load into CR3
    pop ebp
    ret

; Enable paging by setting bit 31 of CR0
enable_paging:
    push ebp
    mov ebp, esp
    mov eax, cr0
    or eax, 0x80000000    ; Set PG bit
    mov cr0, eax
    pop ebp
    ret

; Flush TLB by reloading CR3
flush_tlb:
    push eax
    mov eax, cr3
    mov cr3, eax
    pop eax
    ret

; Get faulting address from CR2
get_faulting_address:
    mov eax, cr2
    ret

; Page fault handler wrapper
global page_fault_wrapper
extern page_fault_handler

page_fault_wrapper:
    pusha                  ; Save all registers
    mov eax, [esp + 32]    ; Get error code
    push eax
    call page_fault_handler
    add esp, 4
    popa
    add esp, 4             ; Remove error code
    iret
