/* ═══════════════════════════════════════════════════════════════════════════
 * FRAY-VGA DRIVER (Mode 13h)
 * Generated by Fraymus - Gen 144
 *
 * Direct Hardware Port Manipulation for VGA Graphics
 *
 * Mode 13h: 320x200 pixels, 256 colors, linear framebuffer at 0xA0000
 *
 * "The machine opens its eyes."
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_VGA_C
#define FRAY_VGA_C

/* ═══════════════════════════════════════════════════════════════════════════
 * VGA HARDWARE PORTS
 * ═══════════════════════════════════════════════════════════════════════════ */

#define VGA_AC_INDEX       0x3C0
#define VGA_AC_WRITE       0x3C0
#define VGA_AC_READ        0x3C1
#define VGA_MISC_WRITE     0x3C2
#define VGA_MISC_READ      0x3CC
#define VGA_SEQ_INDEX      0x3C4
#define VGA_SEQ_DATA       0x3C5
#define VGA_DAC_READ_INDEX 0x3C7
#define VGA_DAC_WRITE_INDEX 0x3C8
#define VGA_DAC_DATA       0x3C9
#define VGA_GC_INDEX       0x3CE
#define VGA_GC_DATA        0x3CF
#define VGA_CRTC_INDEX     0x3D4
#define VGA_CRTC_DATA      0x3D5
#define VGA_INSTAT_READ    0x3DA

/* Screen dimensions */
#define VGA_WIDTH  320
#define VGA_HEIGHT 200

/* Framebuffer address */
static unsigned char* vga_mem = (unsigned char*)0xA0000;

/* Current drawing color */
static unsigned char vga_color = 15;

/* ═══════════════════════════════════════════════════════════════════════════
 * LOW-LEVEL I/O
 * ═══════════════════════════════════════════════════════════════════════════ */

static inline void vga_outb(unsigned short port, unsigned char value) {
    __asm__ volatile ("outb %0, %1" : : "a"(value), "Nd"(port));
}

static inline unsigned char vga_inb(unsigned short port) {
    unsigned char result;
    __asm__ volatile ("inb %1, %0" : "=a"(result) : "Nd"(port));
    return result;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * VGA REGISTER MANIPULATION
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Write to sequencer register */
static void vga_write_seq(unsigned char index, unsigned char value) {
    vga_outb(VGA_SEQ_INDEX, index);
    vga_outb(VGA_SEQ_DATA, value);
}

/* Write to CRTC register */
static void vga_write_crtc(unsigned char index, unsigned char value) {
    vga_outb(VGA_CRTC_INDEX, index);
    vga_outb(VGA_CRTC_DATA, value);
}

/* Write to graphics controller register */
static void vga_write_gc(unsigned char index, unsigned char value) {
    vga_outb(VGA_GC_INDEX, index);
    vga_outb(VGA_GC_DATA, value);
}

/* Write to attribute controller register */
static void vga_write_ac(unsigned char index, unsigned char value) {
    vga_inb(VGA_INSTAT_READ);  /* Reset flip-flop */
    vga_outb(VGA_AC_INDEX, index);
    vga_outb(VGA_AC_WRITE, value);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * MODE 13h INITIALIZATION
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Mode 13h register values */
static unsigned char mode13h_misc = 0x63;

static unsigned char mode13h_seq[] = {
    0x03,  /* Reset */
    0x01,  /* Clocking Mode */
    0x0F,  /* Map Mask */
    0x00,  /* Character Map Select */
    0x0E   /* Sequencer Memory Mode */
};

static unsigned char mode13h_crtc[] = {
    0x5F, 0x4F, 0x50, 0x82, 0x54, 0x80, 0xBF, 0x1F,
    0x00, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x9C, 0x0E, 0x8F, 0x28, 0x40, 0x96, 0xB9, 0xA3,
    0xFF
};

static unsigned char mode13h_gc[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x05, 0x0F, 0xFF
};

static unsigned char mode13h_ac[] = {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
    0x41, 0x00, 0x0F, 0x00, 0x00
};

void vga_init(void) {
    int i;

    /* Write Miscellaneous register */
    vga_outb(VGA_MISC_WRITE, mode13h_misc);

    /* Write Sequencer registers */
    for (i = 0; i < 5; i++) {
        vga_write_seq(i, mode13h_seq[i]);
    }

    /* Unlock CRTC registers */
    vga_write_crtc(0x03, vga_inb(VGA_CRTC_DATA) | 0x80);
    vga_write_crtc(0x11, vga_inb(VGA_CRTC_DATA) & ~0x80);

    /* Make sure they remain unlocked */
    mode13h_crtc[0x03] |= 0x80;
    mode13h_crtc[0x11] &= ~0x80;

    /* Write CRTC registers */
    for (i = 0; i < 25; i++) {
        vga_write_crtc(i, mode13h_crtc[i]);
    }

    /* Write Graphics Controller registers */
    for (i = 0; i < 9; i++) {
        vga_write_gc(i, mode13h_gc[i]);
    }

    /* Write Attribute Controller registers */
    for (i = 0; i < 21; i++) {
        vga_write_ac(i, mode13h_ac[i]);
    }

    /* Lock 16-color palette and enable display */
    vga_inb(VGA_INSTAT_READ);
    vga_outb(VGA_AC_INDEX, 0x20);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * PALETTE CONTROL
 * ═══════════════════════════════════════════════════════════════════════════ */

void vga_set_palette_color(unsigned char index, unsigned char r, unsigned char g, unsigned char b) {
    vga_outb(VGA_DAC_WRITE_INDEX, index);
    vga_outb(VGA_DAC_DATA, r >> 2);  /* VGA uses 6-bit color */
    vga_outb(VGA_DAC_DATA, g >> 2);
    vga_outb(VGA_DAC_DATA, b >> 2);
}

void vga_init_palette(void) {
    /* Standard VGA 256-color palette */
    int i;

    /* First 16 colors: Standard CGA */
    vga_set_palette_color(0,  0,   0,   0);    /* Black */
    vga_set_palette_color(1,  0,   0,   170);  /* Blue */
    vga_set_palette_color(2,  0,   170, 0);    /* Green */
    vga_set_palette_color(3,  0,   170, 170);  /* Cyan */
    vga_set_palette_color(4,  170, 0,   0);    /* Red */
    vga_set_palette_color(5,  170, 0,   170);  /* Magenta */
    vga_set_palette_color(6,  170, 85,  0);    /* Brown */
    vga_set_palette_color(7,  170, 170, 170);  /* Light Gray */
    vga_set_palette_color(8,  85,  85,  85);   /* Dark Gray */
    vga_set_palette_color(9,  85,  85,  255);  /* Light Blue */
    vga_set_palette_color(10, 85,  255, 85);   /* Light Green */
    vga_set_palette_color(11, 85,  255, 255);  /* Light Cyan */
    vga_set_palette_color(12, 255, 85,  85);   /* Light Red */
    vga_set_palette_color(13, 255, 85,  255);  /* Light Magenta */
    vga_set_palette_color(14, 255, 255, 85);   /* Yellow */
    vga_set_palette_color(15, 255, 255, 255);  /* White */

    /* Colors 16-231: 6x6x6 color cube */
    for (i = 16; i < 232; i++) {
        int idx = i - 16;
        int r = (idx / 36) * 51;
        int g = ((idx / 6) % 6) * 51;
        int b = (idx % 6) * 51;
        vga_set_palette_color(i, r, g, b);
    }

    /* Colors 232-255: Grayscale ramp */
    for (i = 232; i < 256; i++) {
        int gray = (i - 232) * 10 + 8;
        vga_set_palette_color(i, gray, gray, gray);
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * DRAWING PRIMITIVES
 * ═══════════════════════════════════════════════════════════════════════════ */

void vga_set_color(unsigned char color) {
    vga_color = color;
}

void vga_clear(unsigned char color) {
    for (int i = 0; i < VGA_WIDTH * VGA_HEIGHT; i++) {
        vga_mem[i] = color;
    }
}

void vga_put_pixel(int x, int y, unsigned char color) {
    if (x >= 0 && x < VGA_WIDTH && y >= 0 && y < VGA_HEIGHT) {
        vga_mem[y * VGA_WIDTH + x] = color;
    }
}

void vga_draw_pixel(int x, int y) {
    vga_put_pixel(x, y, vga_color);
}

unsigned char vga_get_pixel(int x, int y) {
    if (x >= 0 && x < VGA_WIDTH && y >= 0 && y < VGA_HEIGHT) {
        return vga_mem[y * VGA_WIDTH + x];
    }
    return 0;
}

/* Horizontal line (optimized) */
void vga_hline(int x1, int x2, int y, unsigned char color) {
    if (y < 0 || y >= VGA_HEIGHT) return;
    if (x1 > x2) { int t = x1; x1 = x2; x2 = t; }
    if (x1 < 0) x1 = 0;
    if (x2 >= VGA_WIDTH) x2 = VGA_WIDTH - 1;

    unsigned char* p = vga_mem + y * VGA_WIDTH + x1;
    for (int x = x1; x <= x2; x++) {
        *p++ = color;
    }
}

/* Vertical line */
void vga_vline(int x, int y1, int y2, unsigned char color) {
    if (x < 0 || x >= VGA_WIDTH) return;
    if (y1 > y2) { int t = y1; y1 = y2; y2 = t; }
    if (y1 < 0) y1 = 0;
    if (y2 >= VGA_HEIGHT) y2 = VGA_HEIGHT - 1;

    unsigned char* p = vga_mem + y1 * VGA_WIDTH + x;
    for (int y = y1; y <= y2; y++) {
        *p = color;
        p += VGA_WIDTH;
    }
}

/* Bresenham line */
void vga_line(int x1, int y1, int x2, int y2, unsigned char color) {
    int dx = x2 - x1;
    int dy = y2 - y1;
    int sx = dx > 0 ? 1 : -1;
    int sy = dy > 0 ? 1 : -1;
    dx = dx < 0 ? -dx : dx;
    dy = dy < 0 ? -dy : dy;

    int err = (dx > dy ? dx : -dy) / 2;

    while (1) {
        vga_put_pixel(x1, y1, color);
        if (x1 == x2 && y1 == y2) break;
        int e2 = err;
        if (e2 > -dx) { err -= dy; x1 += sx; }
        if (e2 < dy)  { err += dx; y1 += sy; }
    }
}

/* Rectangle (outline) */
void vga_rect(int x, int y, int w, int h, unsigned char color) {
    vga_hline(x, x + w - 1, y, color);
    vga_hline(x, x + w - 1, y + h - 1, color);
    vga_vline(x, y, y + h - 1, color);
    vga_vline(x + w - 1, y, y + h - 1, color);
}

/* Filled rectangle */
void vga_fill_rect(int x, int y, int w, int h, unsigned char color) {
    for (int j = 0; j < h; j++) {
        vga_hline(x, x + w - 1, y + j, color);
    }
}

/* Circle (Bresenham) */
void vga_circle(int cx, int cy, int r, unsigned char color) {
    int x = 0;
    int y = r;
    int d = 3 - 2 * r;

    while (x <= y) {
        vga_put_pixel(cx + x, cy + y, color);
        vga_put_pixel(cx - x, cy + y, color);
        vga_put_pixel(cx + x, cy - y, color);
        vga_put_pixel(cx - x, cy - y, color);
        vga_put_pixel(cx + y, cy + x, color);
        vga_put_pixel(cx - y, cy + x, color);
        vga_put_pixel(cx + y, cy - x, color);
        vga_put_pixel(cx - y, cy - x, color);

        if (d < 0) {
            d += 4 * x + 6;
        } else {
            d += 4 * (x - y) + 10;
            y--;
        }
        x++;
    }
}

/* Filled circle */
void vga_fill_circle(int cx, int cy, int r, unsigned char color) {
    for (int y = -r; y <= r; y++) {
        for (int x = -r; x <= r; x++) {
            if (x * x + y * y <= r * r) {
                vga_put_pixel(cx + x, cy + y, color);
            }
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * GOLDEN RATIO GEOMETRY
 * ═══════════════════════════════════════════════════════════════════════════ */

/* PHI = 1.618033... (scaled by 1000) */
#define PHI_1000 1618

void vga_draw_golden_spiral(int cx, int cy, int size, unsigned char color) {
    int a = size;
    int b = (a * 1000) / PHI_1000;
    int x = cx;
    int y = cy;
    int dir = 0;  /* 0=right, 1=down, 2=left, 3=up */

    for (int i = 0; i < 8 && a > 2; i++) {
        /* Draw arc (quarter circle approximation) */
        int r = a;
        int qx, qy;

        switch (dir) {
            case 0: qx = x + a; qy = y; break;
            case 1: qx = x; qy = y + a; break;
            case 2: qx = x - a; qy = y; break;
            case 3: qx = x; qy = y - a; break;
        }

        /* Draw arc from current point */
        for (int t = 0; t <= 90; t += 5) {
            int px = x + (r * t) / 90;
            int py = y + r - (r * t) / 90;
            vga_put_pixel(px, py, color);
        }

        /* Move to next position */
        x = qx;
        y = qy;

        /* Fibonacci reduction */
        int temp = b;
        b = a - b;
        a = temp;

        dir = (dir + 1) % 4;
    }
}

void vga_draw_fraymus_logo(void) {
    /* Clear screen */
    vga_clear(0);

    /* Golden Rectangle decomposition */
    int base_x = 60;
    int base_y = 30;
    int size = 100;
    int phi_size = (size * 1000) / PHI_1000;  /* ~62 */

    /* Main rectangle (Red) */
    vga_fill_rect(base_x, base_y, size, size, 4);

    /* Phi rectangle (Green) */
    vga_fill_rect(base_x + size, base_y, phi_size, size, 2);

    /* Inner phi rectangle (Blue) */
    int inner_size = size - phi_size;
    vga_fill_rect(base_x + size, base_y + phi_size, phi_size, inner_size, 1);

    /* Deeper recursion (Cyan) */
    int tiny = (inner_size * 1000) / PHI_1000;
    vga_fill_rect(base_x + size, base_y + phi_size, tiny, inner_size, 3);

    /* The Singularity (White pixel at golden point) */
    int singularity_x = base_x + size;
    int singularity_y = base_y + phi_size;
    vga_put_pixel(singularity_x, singularity_y, 15);
    vga_put_pixel(singularity_x + 1, singularity_y, 15);
    vga_put_pixel(singularity_x, singularity_y + 1, 15);
    vga_put_pixel(singularity_x + 1, singularity_y + 1, 15);

    /* Draw golden spiral */
    vga_draw_golden_spiral(singularity_x, singularity_y, phi_size, 14);

    /* Title */
    /* (Would need font rendering - simplified for now) */
}

/* ═══════════════════════════════════════════════════════════════════════════
 * VSYNC & ANIMATION
 * ═══════════════════════════════════════════════════════════════════════════ */

void vga_wait_vsync(void) {
    /* Wait for vertical retrace to end */
    while (vga_inb(VGA_INSTAT_READ) & 8);
    /* Wait for vertical retrace to begin */
    while (!(vga_inb(VGA_INSTAT_READ) & 8));
}

/* ═══════════════════════════════════════════════════════════════════════════
 * DEMO PATTERN
 * ═══════════════════════════════════════════════════════════════════════════ */

void vga_demo(void) {
    vga_init();
    vga_init_palette();
    vga_clear(0);

    /* Gradient background */
    for (int y = 0; y < VGA_HEIGHT; y++) {
        for (int x = 0; x < VGA_WIDTH; x++) {
            vga_put_pixel(x, y, (x + y) / 3);
        }
    }

    /* Draw primitives */
    vga_fill_rect(20, 20, 60, 40, 4);     /* Red rect */
    vga_rect(90, 20, 60, 40, 14);          /* Yellow outline */
    vga_fill_circle(190, 40, 20, 2);       /* Green circle */
    vga_circle(250, 40, 20, 11);           /* Cyan circle outline */

    /* Lines */
    vga_line(20, 80, 300, 120, 15);
    vga_line(20, 120, 300, 80, 12);

    /* Fraymus logo */
    vga_draw_fraymus_logo();
}

#endif /* FRAY_VGA_C */
